export const resources = {
  "side_stretch.jpg": require("../img/side_stretch.jpg"),
  "neck_stretch.jpg": require("../img/neck_stretch.jpg"),
  "cat_cow.jpg": require("../img/cat_cow.jpg"),
  "thread_r.jpg": require("../img/thread_r.jpg"),
  "thread_l.jpg": require("../img/thread_l.jpg"),
  "wrist_stretch.jpg": require("../img/wrist_stretch.jpg"),
  "walk_the_dog.jpg": require("../img/walk_the_dog.jpg"),
  "deep_lunge_r.jpg": require("../img/deep_lunge_r.jpg"),
  "runners_r.jpg": require("../img/runners_r.jpg"),
  "lizard_r.jpg": require("../img/lizard_r.jpg"),
  "deep_lunge_l.jpg": require("../img/deep_lunge_l.jpg"),
  "runners_l.jpg": require("../img/runners_l.jpg"),
  "lizard_l.jpg": require("../img/lizard_l.jpg"),
  "sphinx.jpg": require("../img/sphinx.jpg"),
  "shoulder_twist_r.jpg": require("../img/shoulder_twist_r.jpg"),
  "shoulder_twist_l.jpg": require("../img/shoulder_twist_l.jpg"),
  "childs.jpg": require("../img/childs.jpg"),
  "butterfly.jpg": require("../img/butterfly.jpg"),
  "leg_bend_r.jpg": require("../img/leg_bend_r.jpg"),
  "leg_bend_l.jpg": require("../img/leg_bend_l.jpg"),
  "twist_r.jpg": require("../img/twist_r.jpg"),
  "twist_l.jpg": require("../img/twist_l.jpg"),
  "bridge.jpg": require("../img/bridge.jpg"),
};
